<?php

namespace ContainerRxCx8cz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MV93WtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mV93_wt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mV93_wt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'user' => ['privates', '.errored..service_locator.mV93_wt.Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface', NULL, 'Cannot autowire service ".service_locator.mV93_wt": it references interface "Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'passwordHasher' => '?',
            'user' => 'Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface',
        ]);
    }
}
