<?php

namespace ContainerRxCx8cz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordAuthenticatedUserInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mV93_wt.Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface' shared service.
     *
     * @return \Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mV93_wt": it references interface "Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
