<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMo1ycBq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMo1ycBq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMo1ycBq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMo1ycBq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMo1ycBq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mo1ycBq',
    'container.build_id' => '9a635dac',
    'container.build_time' => 1713227984,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMo1ycBq');
